version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      - webllm
      - brain
    restart: always
    networks:
      - webnet

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run start
    expose:
      - "3000"
    networks:
      - webnet

  backend:
    build: ./backend
    expose:
      - "8080"
    networks:
      - webnet

  webllm:
    build: ./webllm
    expose:
      - "9090"
    networks:
      - webnet

  brain:
    build: ./brain
    expose:
      - "7070"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
